### ISSUE TITLE
Won't work...

### ISSUE THREAD

**Issue by kcuneyt** [nicoSWD/carillon#1]
Hi There, first of all, thanks for putting this up, very brilliant idea... :)

But there is a problem...

I installed all three versions (without uninstalling the old ones)

It happens to play once... but it won't play after another restart...

on the console it says :+1: 

10/3/13 5:39:55.749 PM com.apple.launchd[1]: (com.nicoswd.Carillon[75]) Exited with code: 1

can you offer something? The latest version I installed is 1.2b...

Thank you in advance..

**Comment by kcuneyt** [comment]
Now, it is sometimes working, and sometimes not :) Weird... :s

**Comment by nicoSWD** [comment]
Thanks, I'm glad you like the idea! :) I was very unhappy with other solutions, so I decided to make my own.

My best guess is that the audio kext hasn't been loaded yet when it tries to play the sound. In v1.1b, it attempts to load AppleHDA.kext before playing the sound. Are you using this kext to get the sound working on your machine, or are you using something else? Like HDAEnabler or something similar?

Can you install v1.1b and check the log after booting? (no need to uninstall first)
https://github.com/nicoSWD/Carillon/releases/tag/v1.1b

It should either say "Error loading AppleHDA.kext" or "Loaded AppleHDA.kext".

Thank you for your time and report!

**Comment by kcuneyt** [comment]
Yes, I am using Tolade's HDAEnabler1.kext…

---

Cuneyt Karayalcin
Info : http://www.cuneytkarayalcin.com/

On October 3, 2013 at 6:04:38 PM, Nico Oelgart (notifications@github.com) wrote:

Thanks, I'm glad you like the idea! :) I was very unhappy with other solutions, so I decided to make my own.

My best guess is that the audio kext hasn't been loaded yet when it tries to play the sound. In v1.1b, it attempts to load AppleHDA.kext before playing the sound. Are you using this kext to get the sound working on your machine, or are you using something else? Like HDAEnabler or something similar?

Can you install v1.1b and check the log after booting? (no need to uninstall first)
https://github.com/nicoSWD/Carillon/releases/tag/v1.1b

It should either say "Error loading AppleHDA.kext" or "Loaded AppleHDA.kext".

Thank you for your time and report!

**Comment by nicoSWD** [comment]
I released a version specifically for HDAEnabler.kext. Please give it a try.

https://github.com/nicoSWD/Carillon/releases/tag/v1.3b

**Comment by nicoSWD** [comment]
If it doesn't work, please post the log. :)

**Comment by kcuneyt** [comment]
THANKS!!! now testing... :)

**Comment by kcuneyt** [comment]
It's sometimes (1 out of 5 like) working and most of the time it's not...

I even changed the kext name (was HDA Enabler1.kext) to HDAEnabler.kext - re-inject it - repair permissions... but no chance...

now trying to boot with HDAEnabler=Yes in my boot.plist...

**Comment by nicoSWD** [comment]
Weird... 

Can you open Console.app and search for errors containing Carillon? Does it say the kext is loaded or not?

Thanks again for your time! Finally someone willing to help me with this. :)

**Comment by nicoSWD** [comment]
The name of the kext isn't that important, since the system uses the identifier, which is _com.kext.HDAEnabler_.

What may be important is the location, though. Is it in your /Extra folder, or in /S/L/E/?

**Comment by kcuneyt** [comment]
It's in S/L/E...

And the console says : 10/3/13 6:51:56.696 PM Carillon[72]: HALDefaultDevice::GetDefaultDevice: server returned 0 for the default device, so picking one locally

**Comment by kcuneyt** [comment]
And it's not working again...

**Comment by kcuneyt** [comment]
4 restarts : first two working, the other two are not :) ?

**Comment by nicoSWD** [comment]
This is crazy haha. The times when it actually works, does the log show "Loaded HDAEnabler1.kext"?

**Comment by nicoSWD** [comment]
I released a debug version here:

https://github.com/nicoSWD/Carillon/releases/tag/v1.4b

Can you try this and post _all_ related log entries from the Console?

Thank you! :)

**Comment by kcuneyt** [comment]
Hello There, I was out...

**Comment by kcuneyt** [comment]
So this is the output after the debug version (installed and restart - working now) - i will try another restart after writing this message...

10/3/13 7:05:34.734 PM Carillon[72]: HALDefaultDevice::GetDefaultDevice: server returned 0 for the default device, so picking one locally

10/4/13 3:04:57.921 PM sudo[485]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.RhrSvq/Scripts/com.nicoswd.carillon.com.nicoswd.Carillon.pkg.uuJd6C ; USER=root ; COMMAND=/usr/sbin/chown root:wheel /System/Library/LaunchDaemons/com.nicoswd.Carillon.plist

10/4/13 3:04:57.963 PM sudo[488]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.RhrSvq/Scripts/com.nicoswd.carillon.Carillon.pkg.k2lBdl ; USER=root ; COMMAND=/usr/sbin/chown root:wheel /usr/local/bin/Carillon

**Comment by kcuneyt** [comment]
and after the restart : 

So this is the output after the debug version (installed and restart - working now) - i will try another restart after writing this message...

10/3/13 7:05:34.734 PM Carillon[72]: HALDefaultDevice::GetDefaultDevice: server returned 0 for the default device, so picking one locally

10/4/13 3:04:57.921 PM sudo[485]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.RhrSvq/Scripts/com.nicoswd.carillon.com.nicoswd.Carillon.pkg.uuJd6C ; USER=root ; COMMAND=/usr/sbin/chown root:wheel /System/Library/LaunchDaemons/com.nicoswd.Carillon.plist

10/4/13 3:04:57.963 PM sudo[488]:     root : TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.RhrSvq/Scripts/com.nicoswd.carillon.Carillon.pkg.k2lBdl ; USER=root ; COMMAND=/usr/sbin/chown root:wheel /usr/local/bin/Carillon

not working, and same entries after the restart... :(

**Comment by kcuneyt** [comment]
I have one suggestion : I have changed some timeouts for faster shutdown and reboot, is it maybe causing this?

Here are the terminal commands I used for faster shutdown : 

sudo defaults write /System/Library/LaunchDaemons/com.apple.coreservices.appleevents ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchDaemons/com.apple.securityd ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchDaemons/com.apple.diskarbitrationd ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchAgents/com.apple.coreservices.appleid.authentication ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchDaemons/com.apple.SystemStarter ExitTimeOut -int 1

sudo defaults write /System/Library/LaunchDaemons/com.apple.SystemStarter ExitTimeOut -int 1

**Comment by kcuneyt** [comment]
Hi There...

**Comment by kcuneyt** [comment]
Any Solutions for me? :)

**Comment by nicoSWD** [comment]
Heya!

Sorry, I haven't forgotten about it. I'm still working on another release at the moment, but don't have much time unfortunately.

I don't _think_ your timeout changes have to do with it, but I'm not 100% sure.

**Comment by kcuneyt** [comment]
here is the latest console output : 

10/12/13 7:27:30.989 PM Carillon[72]: HALDefaultDevice::GetDefaultDevice: server returned 0 for the default device, so picking one locally

**Comment by kcuneyt** [comment]
Hey There, just FYI, it started working on Mavericks, every time I reboot :)

**Comment by nicoSWD** [comment]
Awesome! Not sure I can explain why, but I'm glad it works.

Thank you!
