### ISSUE TITLE
Won't boot anymore after install

### ISSUE THREAD

**Issue by polyzargone** [nicoSWD/carillon#2]
Hi,

I've just downladed abd installed carillon with ML 10.8.5 and I can't boot anymore. I've got an error about APCI and then kernel panic. Tried to boot with -v -x -f -F or with the Tony'sMac bootCD but I can't access my desktop, got a KP every time. My config worked fine until then and I don't know what to do. What files has been installed and where, If I could access my desktop, I'll remove them but I don't know where to begin ?

Help ! plz

**Comment by nicoSWD** [comment]
Hi,

this is very weird, it really shouldn't cause any kernel panics. 

Try booting with the -s flag, this should show you the command prompt. There, type _mount disk1s0_ (If you have multiple HDDs, you may have to change the numbers, eg disk2s0 etc)

After that, type:

rm /Volumes/[Volume name]/usr/local/bin/Carillon

And

rm /Volumes/[Volume name]/System/Library/LaunchDaemons/com.nicoswd.Carillon.plist

Sorry for the inconvenience. It's a strange issue you're having.
