### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by polyzargone** [nicoSWD/carillon#3]
![dsc_0104](https://f.cloud.github.com/assets/5621149/1276394/1c7a93d6-2e64-11e3-9263-2821ea95aa3c.jpg)
![dsc_0105](https://f.cloud.github.com/assets/5621149/1276395/1c922de8-2e64-11e3-804c-b8055149a392.jpg)

Here's the messages…

**Comment by kcuneyt** [comment]
Have you changed some .kext(s) recently?

**Comment by polyzargone** [comment]
Hi,

Thanks for the reply.
Last things I did as far as I can remember was to install Chameleon r2265 and you app. I was also playing around with MyHack and Pandora’s box to make a Mavericks GM USB Stick install but nothing else.

I finally boot up with Windows 8 and used MacDrive 9 to remove the files from the Mac HD such as your com.nicoswd.Carillon.plist and /usr/local/bin/Carillon. I also trashed the AppleHDA.kext and verified the chameleon.boot.plist was OK but I still have KP.

The thing I don’t understand is that NONE of my install USB Stick or previous OS 10.8.5 bootables installs can boot. No matter what I use, I still have the AppleACPIPlatform problem which makes me think it’s not an issue due to your app but with something else. But I don’t know what, my Win 8 and xubuntu installs works fine, I didn’t changed anything in the BIOS, no hardware changes, nothing.

**Comment by nicoSWD** [comment]
Yeah, I'm pretty sure it's safe to say at this point that your problem is not related to Carillon.

Have you rebuilt your kext cache after removing the AppleHDA?

**Comment by polyzargone** [comment]
OK,

Finally fix the problem by overwriting AppleACPIPlatform.kext with a backup one. Everything is now OK. Hope you won't mind if I do not retry your app for now :-)

Now, let's go to Mavericks GM (a Time Machine backup is on the way before I install)
Thx for replies,

**Comment by nicoSWD** [comment]
Hehe, yeah no problem. 

Going to close this now.
